
# setlist.pl 09/04/13 31/05/15 15/10/15 04/12/15

# Creates a setlist text file from a folder of flac files

use strict;
use warnings;

use MyLib qw(prompt);
use File::Find;

my @flacs;
my $txtfile = "setlist.txt";

main ();

sub main {
	my (@sorted, @presorted, $fh);
	my ($title, $flacfile, $junk);

	my $dir = prompt ("Directory (c:/mine/music/) ".":");
	my $path = "c:/mine/music/".$dir;
	chdir ($path) or die "\nUnable to find folder $path";

	find ( sub { push @flacs, $_ if $_ =~ /.flac$/	}, $path);
	@presorted = sort @flacs;
	for (@presorted) {
		($junk, $flacfile) = split (/\d /, $_);
		($title, $junk) = split ('\.', $flacfile);
		push @sorted, $title;
	}

# Write to disc

	open ($fh, '>', $txtfile) or die "\n\n Can't open new setlist file !!!";
	write_text_file ($fh, \@sorted);
	close $fh;

# Write to screen

	open ($fh, '>-'); # opens STDOUT
	write_text_file ($fh, \@sorted);
	close $fh;
	print "\n\nText file completed.\n";
}

sub write_text_file {
	my ($fh, $sortedref) = @_;

	print $fh "Text file generated by setlist.pl\n";

	for my $flacfile (@$sortedref) {
		print $fh "\n$flacfile";
	}
	print $fh "\n";
}
